<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>0.0.3</Version>
		<FileVersion>0.0.3</FileVersion>
		<AssemblyVersion>0.0.3</AssemblyVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Cadmus.Mongo" Version="16.0.7" />
		<PackageReference Include="Cadmus.Seed.Codicology.Parts" Version="9.0.7" />
		<PackageReference Include="Cadmus.Seed.General.Parts" Version="16.0.7" />
		<PackageReference Include="Cadmus.Seed.Ndp.Parts" Version="16.0.6" />
		<PackageReference Include="Cadmus.Seed.NdpBooks.Parts" Version="16.0.6" />
		<PackageReference Include="Cadmus.Seed.Philology.Parts" Version="16.0.7" />
		<PackageReference Include="Fusi.Antiquity" Version="6.0.0" />
		<PackageReference Include="Fusi.Microsoft.Extensions.Configuration.InMemoryJson" Version="5.0.0" />
	</ItemGroup>

</Project>
